spring.application.name=todoout

spring.datasource.url=jdbc:mysql://localhost:3306/todooutdb
spring.datasource.username=root
spring.datasource.password=mavqyn-vordek-3vUmgy

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
